type User @table {
  name: String!
  email: String!
  role: String!
  phoneNumber: String
  avatarUrl: String
}

type Category @table {
  name: String!
  description: String
}

type Item @table {
  title: String!
  price: Float!
  description: String
  imageUrl: String
  category: Category!
}

type Order @table {
  user: User!
  status: String!
  createdAt: Timestamp!
  scheduledDate: Timestamp
  totalAmount: Float
}

type OrderItem @table {
  order: Order!
  item: Item!
  quantity: Int!
  notes: String
}